from abc import ABC, abstractmethod


"""
Abstract class declaring functionality available in the API
"""
class TwitterAPI(ABC):
    @abstractmethod
    def postTweet(self, user_id, tweet_text):
        """
        :param user_id:
        :param tweet_text: tweet text
        :return: Insert tweet into Twitter database
        """
        pass

    @abstractmethod
    def getTimeline(self, user_id):
        """
        :param user_id: ID of user
        :return: List of Tweet objects of user consisting of all tweets generated by other users current user follows
        """
